### ISSUE TITLE
API Usage

### ISSUE THREAD

**Issue by savasturk** [akshayvernekar/telloArduino#2]
How we can use this(API usage
// 1. Create the object
Tello tello

// 2. Initialise the Object after your device gets the IP address
tello.init()

// 3 .Once the object is initalised you can use the various fubnctions to send commands to tello.) section ?

**Comment by akshayvernekar** [comment]
Readme updated with API Info.

**Comment by savasturk** [comment]
Sorry, but I executed "tello_example.ino" and I recieved this error.

tello_example:62: error: variable or field 'WiFiEvent' declared void

tello_example:62: error: 'WiFiEvent_t' was not declared in this scope

C:\Users\Å?EROO\Desktop\telloArduino-master\tello_example\tello_example.ino: In function 'void connectToWiFi(const char*, const char*)':

tello_example:51: error: no matching function for call to 'WiFiClass::disconnect(bool)'

C:\Users\Å?EROO\Desktop\telloArduino-master\tello_example\tello_example.ino:51:23: note: candidate is:

In file included from D:\Ardunio\Arduino\libraries\tello/Tello.h:12:0,

                 from C:\Users\Å?EROO\Desktop\telloArduino-master\tello_example\tello_example.ino:1:

D:\Ardunio\Arduino\libraries\WiFi\src/WiFi.h:130:9: note: int WiFiClass::disconnect()

     int disconnect(void);

         ^

D:\Ardunio\Arduino\libraries\WiFi\src/WiFi.h:130:9: note:   candidate expects 0 arguments, 1 provided

tello_example:53: error: 'class WiFiClass' has no member named 'onEvent'

tello_example:53: error: 'WiFiEvent' was not declared in this scope

tello_example:56: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]

In file included from D:\Ardunio\Arduino\libraries\tello/Tello.h:12:0,

                 from C:\Users\Å?EROO\Desktop\telloArduino-master\tello_example\tello_example.ino:1:

D:\Ardunio\Arduino\libraries\WiFi\src/WiFi.h:79:9: error:   initializing argument 1 of 'int WiFiClass::begin(char*, const char*)' [-fpermissive]

     int begin(char* ssid, const char *passphrase);

         ^

C:\Users\Å?EROO\Desktop\telloArduino-master\tello_example\tello_example.ino: At global scope:

tello_example:62: error: variable or field 'WiFiEvent' declared void

tello_example:62: error: 'WiFiEvent_t' was not declared in this scope

exit status 1
variable or field 'WiFiEvent' declared void

Could yo help me, please?

**Comment by akshayvernekar** [comment]
I had tested with an earlier version of Arudino IDE, I will probably have a look tomorrow with the latest version and keep you guys updated . I am closing this issue , will update on the other thread.
